In [9]:
import numpy as np

#Array Creation 
a = np.array([[1, 2, 3, 4],
				[5, 2, 4, 2],
				[1, 2, 0, 1]])
print(a)

#reshape 
newArr = a.reshape(2,2,3)
print(newArr)

#flatten
arr = np.array([[1, 2, 3], [4, 5, 6]])
flarr = arr.flatten()
print(flarr)

#Arrange
print(np.arange(4, 10))


[[1 2 3 4]
 [5 2 4 2]
 [1 2 0 1]]
[[[1 2 3]
  [4 5 2]]

 [[4 2 1]
  [2 0 1]]]
[1 2 3 4 5 6]
[4 5 6 7 8 9]
